
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: guardian_db
      POSTGRES_USER: guardian
      POSTGRES_PASSWORD: guardian123!@#
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  guardian-backend:
    build: ./backend/guardian
    environment:
      - DATABASE_URL=postgresql://guardian:guardian123!@#@postgres:5432/guardian_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    restart: unless-stopped

  nexus-backend:
    build: ./backend/nexus
    environment:
      - DATABASE_URL=postgresql://guardian:guardian123!@#@postgres:5432/guardian_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - guardian-backend
      - nexus-backend
    restart: unless-stopped

volumes:
  postgres_data:
