// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvdwvisahnnitepsdova.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2ZHd2aXNhaG5uaXRlcHNkb3ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDE3NDIsImV4cCI6MjA2Njg3Nzc0Mn0.HR-obXu21iMpDmylBKDFtAp2W9L9xC-u8CoI8I_r6pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});